"""Generates ``examples/WHAT_EACH_RULE_CATCHES.md``.

The test suite proves the rules fire, but only to whoever runs pytest. This
proves it to a reader: for every rule, the sample workbook that breaks it and
the exact row that appears in the validation report.

Rows are read out of the generated report workbooks, not printed from the
library, so what the document shows is what the analyst actually receives.

Regenerate after changing any rule::

    python3 tests/show_failures.py
"""

from __future__ import annotations

import contextlib
import io
import os
import sys
import tempfile
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "tests"))

from make_fixtures import FIXTURES  # noqa: E402
from ul_fund_checks import RULES  # noqa: E402
from validate import main  # noqa: E402

CATALOGUE = ROOT / "examples" / "WHAT_EACH_RULE_CATCHES.md"
CLEAN = ROOT / "examples" / "good" / "UL_FUND_DATA_Q4_2025.xlsx"
BAD_DIR = ROOT / "examples" / "bad"
FIRST_DATA_ROW = 9

HEADER = """# What each rule catches

Generated by `tests/show_failures.py`. Do not edit by hand.

Every rule has a sample workbook in `examples/bad/` that breaks it and nothing
else. The rows below are read out of the validation report each sample
produces, so this is what an analyst would actually see — not a description of
it.

`tests/test_every_rule_fails.py` asserts each sample trips its own rule **and
no others**, and fails if any rule has no sample.
"""


def report_for(source: Path, workdir: Path):
    out = workdir / f"{source.stem}_validation.xlsx"
    # validate.py prints a chat summary; that is noise when generating a document.
    with contextlib.redirect_stdout(io.StringIO()):
        main([str(source), "--out", str(out), "--no-recalc"])
    ws = load_workbook(out, data_only=True).worksheets[0]
    rows = [
        {
            "rule": ws.cell(r, 1).value,
            "scope": ws.cell(r, 3).value,
            "status": ws.cell(r, 4).value,
            "details": ws.cell(r, 5).value,
        }
        for r in range(FIRST_DATA_ROW, ws.max_row + 1)
    ]
    return ws, rows


def build(workdir: Path) -> str:
    lines = [HEADER]

    ws, rows = report_for(CLEAN, workdir)
    passes = sum(1 for r in rows if r["status"] == "PASS")
    lines.append(
        f"\n## The clean sample\n\n"
        f"`examples/good/{CLEAN.name}` — {passes} checks pass, none fail. "
        f"The report header reads `{ws['B6'].value}`.\n"
    )

    by_rule = {f.rule: f for f in FIXTURES}

    lines.append("\n## Summary\n")
    lines.append("| Rule | Sample workbook | The defect |")
    lines.append("| --- | --- | --- |")
    for rule in RULES:
        fixture = by_rule.get(rule.id)
        if fixture is None:
            lines.append(f"| {rule.id} | *no sample* | — |")
        else:
            lines.append(f"| {rule.id} | `{fixture.filename}` | {fixture.note} |")

    lines.append("\n## Detail\n")
    for rule in RULES:
        lines.append(f"### {rule.id} — {rule.description}\n")
        fixture = by_rule.get(rule.id)
        if fixture is None:
            lines.append("No sample. This rule has never been shown to detect anything.\n")
            continue
        _, rows = report_for(BAD_DIR / fixture.filename, workdir)
        failures = [r for r in rows if r["status"] == "FAIL"]
        lines.append(f"`examples/bad/{fixture.filename}` — {fixture.note}\n")
        lines.append("| Rule | Sheet / column | Status | Details |")
        lines.append("| --- | --- | --- | --- |")
        for row in failures:
            details = str(row["details"]).replace("|", "\\|")
            lines.append(f"| {row['rule']} | {row['scope']} | {row['status']} | {details} |")
        stray = {r["rule"] for r in failures} - {rule.id}
        if stray:
            lines.append(f"\n> This sample also trips {sorted(stray)}, which it should not.")
        passes = sum(1 for r in rows if r["status"] == "PASS")
        lines.append(f"\n{passes} other checks pass on this workbook.\n")

    return "\n".join(lines).rstrip() + "\n"


def main_() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        CATALOGUE.write_text(build(Path(tmp)), encoding="utf-8")
    covered = sum(1 for r in RULES if any(f.rule == r.id for f in FIXTURES))
    print(f"wrote {CATALOGUE.relative_to(ROOT)} — {covered}/{len(RULES)} rules demonstrated")


if __name__ == "__main__":
    main_()
